"""Змінено поле created_at у моделі Comments

Revision ID: 3712c94d7419
Revises: 4670b13bc913
Create Date: 2025-01-12 16:04:05.482261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3712c94d7419'
down_revision: Union[str, None] = '4670b13bc913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
