name: FastAPI CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test1234
          POSTGRES_DB: diplomadb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov

    - name: Run migrations
      env:
        SQLALCHEMY_DATABASE_URL: postgresql://postgres:test1234@localhost:5432/diplomadb
      run: |
        alembic upgrade head

    - name: Run tests with coverage
      env:
        SQLALCHEMY_DATABASE_URL: postgresql://postgres:test1234@localhost:5432/diplomadb
        SECRET_KEY: "197b2c37c391bed93fe80344fe73b806947a65e36206e05a1a23c2fa12702fe3"
        ALGORITHM: "HS256"
        TEST_DATABASE_URL: "sqlite:///./test.db"
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        pytest --cov=./ --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        fail_ci_if_error: true

  e2e-tests:
    needs: test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test1234
          POSTGRES_DB: diplomadb
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Chrome
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install ./google-chrome-stable_current_amd64.deb

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      env:
        SQLALCHEMY_DATABASE_URL: postgresql://postgres:test1234@localhost:5432/diplomadb
      run: |
        alembic upgrade head

    - name: Start FastAPI server
      env:
        SQLALCHEMY_DATABASE_URL: postgresql://postgres:test1234@localhost:5432/diplomadb
        SECRET_KEY: "197b2c37c391bed93fe80344fe73b806947a65e36206e05a1a23c2fa12702fe3"
        ALGORITHM: "HS256"
        TEST_DATABASE_URL: "sqlite:///./test.db"
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        python main.py &
        sleep 5  # Чекаємо поки сервер запуститься

    - name: Run E2E tests
      run: |
        pytest tests/test_e2e_registration.py -v

    - name: Store test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: |
          ./allure-results
          ./coverage.xml 